Make modbus  available to plugins
kbialek/deye-inverter-mqtt pull request #211
Opened 2024-11-12 06:12 UTC by belowm

This allows plugins to access the modbus by adding `DeyeModbus` to `PluginContext`.

2024-11-12 21:45 UTC, kbialek commented
What do you want to use modbus for in the plugin?

2024-11-14 18:25 UTC, belowm commented
> What do you want to use modbus for in the plugin?

Because I'd like to mutate a specific modbus register in my plugin:

```python
class DeyeGridChargeCurrentEventProcessor(DeyeEventProcessor):
    def __init__(
        self, logger_config: DeyeLoggerConfig, mqtt_client: DeyeMqttClient, modbus: DeyeModbus
    ):
        self.__log = logger_config.logger_adapter(logging.getLogger(DeyeGridChargeCurrentEventProcessor.__name__))
        self.__logger_config = logger_config
        self.__mqtt_client = mqtt_client
        self.__modbus = modbus
        self.__gridcharge_current_topic_suffix = "settings/gridcharge_current"

    def get_id(self):
        return "gridcharge_current"

    def get_description(self):
        return "Gridcharge Current over MQTT"

    def initialize(self):
        self.__mqtt_client.subscribe_command_handler(
            self.__logger_config.index, self.__gridcharge_current_topic_suffix, self.handle_command
        )

    def handle_command(self, client: Client, userdata, msg: MQTTMessage):
        try:
            gridcharge_current = int(msg.payload)
        except ValueError:
            self.__log.error("Invalid Gridcharge Current value: %s", msg.payload)
            return

        if gridcharge_current not in range(161):
            self.__log.error("Given Gridcharge Current invalid: %f", gridcharge_current)
            return

        self.__log.info("Setting Gridcharge Current to %f", gridcharge_current)

        if self.__modbus.write_register_uint(int(128), gridcharge_current):
            self.__log.info("Register updated")
        else:
            self.__log.error("Updating register failed")

class DeyePlugin:
    def __init__(self, plugin_context: DeyePluginContext):
        self.processor = DeyeGridChargeCurrentEventProcessor(plugin_context.config.logger_configs[0], plugin_context.mqtt_client, plugin_context.modbus)

    def get_event_processors(self) -> [DeyeEventProcessor]:
        return [self.processor]
```

I'm not much of a python guy, maybe there's a better way to archive this? :)

2024-12-04 19:39 UTC, kbialek requested changes

2024-12-04 19:39 UTC, kbialek commented on src/deye_processor_factory.py
> +from deye_modbus import DeyeModbus
@belowm Remove this extra import, otherwise the PR check will not pass and will block the merge of the PR

2025-05-03 16:17 UTC, kbialek commented
Closing as stale

2025-05-03 16:17 UTC, closed without merging